services:
  discord-bot:
    build: .
    env_file: .env
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./db:/app/db

  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gdg_updates}
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
