FROM oven/bun:1-alpine

WORKDIR /app

COPY . .

RUN bun install

VOLUME [ "/app/db" ]

# Environment variables
ENV BOT_TOKEN=${BOT_TOKEN} \
  BOT_CLIENT_ID=${BOT_CLIENT_ID} \
  BOT_CLIENT_SECRET=${BOT_CLIENT_SECRET} \
  BOT_PUBLIC_KEY=${BOT_PUBLIC_KEY} \
  POSTGRES_USER=${POSTGRES_USER} \
  POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
  POSTGRES_DB=${POSTGRES_DB} \
  POSTGRES_HOST=${POSTGRES_HOST} \
  POSTGRES_PORT=${POSTGRES_PORT} \
  PORT=${PORT}

EXPOSE 8080

CMD ["bun", "run", "index.ts"]