[project]
name = "gdg-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py>=2.6.3",
    "fastapi>=0.116.2",
    "groq>=0.31.1",
    "jishaku>=2.6.0",
    "motor>=3.7.1",
    "pillow>=11.3.0",
    "psutil>=7.0.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "speedtest-cli>=2.1.3",
]
